#!/usr/bin/env python

# Created by Michael Gilliland
# Date: Fri Jan 25 17:51:03 EST 2013
# 
# 

from package_container import PackageContainer

packages = {'Eclipse': 'eclipse',
            'Eclipse C/C++': 'eclipse-cdt',
            'MonoDevelop': 'monodevelop',
            'Mono Python': 'monodevelop-python',

container = PackageContainer("Python", 'python', packages)

